version: "3"

services:
  api-dev:
    image: api-dev
    build: .
    container_name: api-dev
    ports:
      - "8000:80"
    volumes:
      - "./build_output:/app"
    external_links:
      - mysql_shared_instance:mysql_local
    networks:
      - default

networks:
  default:
    external:
      name: base_network
