version: "3"
services:
  mysql:
    image: "mysql:8.0"
    restart: always
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --max_allowed_packet=1000000000,
      ]
    container_name: mysql_shared_instance
    environment:
      - MYSQL_ROOT_PASSWORD=sioux@asia
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=sioux
      - MYSQL_PASSWORD=sioux@asia
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - "./volume:/var/lib/mysql"
