version: "2"

services:
  giveandtake-api-dev:
    restart: always
    image: giveandtake-api-dev
    build:
      context: build_output/api
      dockerfile: Dockerfile

    container_name: giveandtake-api-dev
    volumes:
      - "./build_output/api:/app"
    external_links:
      - mysql_shared_instance:mysql_local
