version: "3"

services:
  base-api:
    image: base-api
    build: .
    container_name: base-api
    ports:
      - "8000:80"
    volumes:
      - "./build_output/api:/app"
    external_links:
      - mysql_shared_instance:mysql_local
