version: "2"

services:
  giveandtake-api-dev:
    restart: always
    image: giveandtake-api-dev
    build: 
      context: output/api
      dockerfile: Dockerfile
  
    container_name: giveandtake-api-dev
    volumes:
      - "./output/api/app:/app"
    labels:
      - traefik.backend=giveandtake_api_dev
      - traefik.frontend.rule=Host:api.dev.chovanhan.asia
      - traefik.docker.network=traefik_proxy
      - traefik.port=80
    external_links:
      - mysql_shared_instance:mysql_local
    networks:
      - proxy

networks:
  proxy:
    external:
      name: traefik_proxy 
